### ISSUE TITLE
Just working in a specific repository in my machine

### ISSUE THREAD

**Issue by joaoofreitas** [carlos-menezes/glog#1]
Hello __my fellow friend__, Carlos 👋

I'm currently testing your new awesome project. And it's awesome!
But it is just working with your specific repository made for testing... 
(At least in my machine...)
Am I doing something wrong?

Let me know if you want help contributing to this or any other project.
Best Regards, João Freitas

**Comment by carlos-menezes** [comment]
Hey!

What does your `config.yml` look like?

**Comment by joaoofreitas** [comment]
It looks like this @carlos-menezes!

```
title: Blog
name: João Freitas
tagline: by João Freitas
username: joaoofreitas
repository: cross-platform-internet-controller
options:
  show_comments: true
  show_edits: true
  index_mode: id
```
